<?php
/**
 * @file musth_license.module
 *
 * @brief Our basic and very stripped down Commerce License
 *
 * @ingroup musthlicense
 *
 * Created by PhpStorm.
 * User: www-data
 * Date: 20/05/14
 * Time: 18:50
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Here it's where the ctools module comes to see where we define
 * our custom license (subfolder plugins)
 */
function musth_license_ctools_plugin_directory($owner, $plugin_type) {
    if ($owner == 'commerce_license') {
        return "plugins/$plugin_type";
    }
}
