<?php
/**
 * @file musth_license.inc
 *
 * @brief Definition of the ctools plugin
 *
 * What is said here is just that our plugin is the class MusthLicense
 * defined in MusthLicense.class.php
 * @see MusthLicense.class.php
 *
 * @ingroup musthlicense
 *
 * Created by PhpStorm.
 * User: www-data
 * Date: 17/03/14
 * Time: 18:06
 */

$plugin = array(
    'title' => t('Musth license'),
    'class' => 'MusthLicense',
    'weight' => 1,
);
